apiVersion: v1
kind: Namespace
metadata:
  name: aergia-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aergia-leader-election-role
  namespace: aergia-backend
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: aergia-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aergia-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aergia-leader-election-rolebinding
  namespace: aergia-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aergia-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: aergia-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aergia-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aergia-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: aergia-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aergia-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aergia-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: aergia-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: aergia-controller-manager-metrics-service
  namespace: aergia-backend
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  namespace: aergia-backend
  name: aergia-backend
  labels:
    app.kubernetes.io/name: aergia-backend
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: backend
    port: 80
    targetPort: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: aergia-controller-manager
  namespace: aergia-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --debug=true
        - --service-idler-cron=*/1 * * * * # Every minute
        - --skip-hit-check
        # Setting the environment variable DEBUG we can see the headers sent 
        # by the ingress controller to the backend in the client response.
        env:
        - name: DEBUG
          value: "true"
        # - name: DRY_RUN
        #   value: "true"
        - name: POD_CHECK_INTERVAL
          value: "2"
        ports:
        - containerPort: 5000
          name: backend
        command:
        - /manager
        image: amazeeiolocal/aergia:test-tag
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10