apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    lagoon.sh/environmentType: development
    lagoon.sh/project: test-project
    lagoon.sh/projectIdlingEnabled: "true"
    lagoon.sh/projectAutoIdle: "1"
    lagoon.sh/environment: development
    lagoon.sh/environmentIdlingEnabled: "true"
    lagoon.sh/environmentAutoIdle: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: development
  labels:
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: development
  labels:
    idling.amazee.io/watch: 'true'
    lagoon.sh/environment: development
    lagoon.sh/service: nginx
  annotations:
    idling.amazee.io/idled: 'false'
    idling.amazee.io/unidle-replicas: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        lagoon.sh/environment: development
        lagoon.sh/service: nginx
    spec:
      containers:
      - name: nginx
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: development
  # add annotation to expose the headers to the backend service for 503 only
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
  labels:
    lagoon.sh/autogenerated: "true"
spec:
  rules:
  - host: development.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
  namespace: development
  labels:
    idling.amazee.io/watch: 'true'
    lagoon.sh/environment: development
    lagoon.sh/service: cli
  # annotations:
  #   idling.amazee.io/idled: 'false'
  #   idling.amazee.io/unidle-replicas: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
        lagoon.sh/environment: development
        lagoon.sh/service: cli
    spec:
      containers:
      - name: cli
        image: nginxdemos/nginx-hello:plain-text
        env:
        - name: CRONJOBS
          value: "14,29,44,59 * * * * drush cron"